STEAMWORKS_SDK_PATH ?= $(HOME)/Developer/steamworks-sdk

STEAMWORKS_SDK_PUBLIC    := $(STEAMWORKS_SDK_PATH)/public
STEAMWORKS_SDK_REDIS_BIN := $(STEAMWORKS_SDK_PATH)/redistributable_bin

STEAMWORKS_SDK_LIBDIR_LINUX64 := $(STEAMWORKS_SDK_REDIS_BIN)/linux64
STEAMWORKS_SDK_LIBDIR_WIN64   := $(STEAMWORKS_SDK_REDIS_BIN)/win64
STEAMWORKS_SDK_LIBDIR_OSX     := $(STEAMWORKS_SDK_REDIS_BIN)/osx

STEAMWORKS_SDK_LIB_LINUX64 := $(STEAMWORKS_SDK_LIBDIR_LINUX64)/libsteam_api.so
STEAMWORKS_SDK_LIB_WIN64   := $(STEAMWORKS_SDK_LIBDIR_WIN64)/steam_api64.dll
STEAMWORKS_SDK_LIB_OSX     := $(STEAMWORKS_SDK_LIBDIR_OSX)/libsteam_api.dylib

STEAM_APP_ID ?= 0
export STEAM_APP_ID

STEAM_ENABLED := 0
ifneq ($(STEAM_APP_ID),0)
STEAM_ENABLED := 1
endif

ifeq ($(STEAM_ENABLED),1)

ifeq ($(filter -DSTEAM_APP_ID=%,$(CDEFS)),)
override CDEFS += -DSTEAM_APP_ID=$(STEAM_APP_ID)
endif

ifeq ($(STEAM_PLATFORM),linux64)
STEAM_LIBDIR := $(STEAMWORKS_SDK_LIBDIR_LINUX64)
STEAM_LIB    := $(STEAMWORKS_SDK_LIB_LINUX64)
STEAM_LDLIB  := -lsteam_api
else ifeq ($(STEAM_PLATFORM),win64)
STEAM_LIBDIR := $(STEAMWORKS_SDK_LIBDIR_WIN64)
STEAM_LIB    := $(STEAMWORKS_SDK_LIB_WIN64)
STEAM_LDLIB  := -lsteam_api64
else ifeq ($(STEAM_PLATFORM),osx)
STEAM_LIBDIR := $(STEAMWORKS_SDK_LIBDIR_OSX)
STEAM_LIB    := $(STEAMWORKS_SDK_LIB_OSX)
STEAM_LDLIB  := -lsteam_api
else
$(error STEAM_PLATFORM must be linux64, win64, or osx)
endif

ifeq ($(wildcard $(STEAM_LIB)),)
$(error STEAM_APP_ID set but Steamworks redistributable missing: $(STEAM_LIB) (STEAMWORKS_SDK_PATH=$(STEAMWORKS_SDK_PATH)))
endif

EXTERNAL_FLAGS += -isystem $(STEAMWORKS_SDK_PUBLIC)
LDFLAGS += -L$(STEAM_LIBDIR)
LDLIBS += $(STEAM_LDLIB)

ifeq ($(STEAM_PLATFORM),linux64)
LDFLAGS += -Wl,-rpath,'$$ORIGIN'
endif
ifeq ($(STEAM_PLATFORM),osx)
LDFLAGS += -Wl,-rpath,@loader_path
endif

endif
