#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"
#include "base/types.h"

enum body_flag {
  BODY_FLAG_NONE = 0,

  BODY_FLAG_DISABLED,
  BODY_FLAG_GRAVITY,
  BODY_FLAG_STATIC,

  BODY_FLAG_NUM_COUNT,
};


static const str8 BODY_FLAG_LABELS[BODY_FLAG_NUM_COUNT] = {
  [BODY_FLAG_NONE] = str8_lit_comp("NONE"),
  [BODY_FLAG_DISABLED] = str8_lit_comp("DISABLED"),
  [BODY_FLAG_GRAVITY] = str8_lit_comp("GRAVITY"),
  [BODY_FLAG_STATIC] = str8_lit_comp("STATIC"),
};

static u8 BODY_FLAG_BITMASKS[4] = {
  [BODY_FLAG_NONE] = 0,
  [BODY_FLAG_DISABLED] = 2,
  [BODY_FLAG_GRAVITY] = 4,
  [BODY_FLAG_STATIC] = 8,
};

